# Generated by Django 4.2.5 on 2023-10-03 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0006_profile_delete_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='othertext',
            name='date_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
