# Generated by Django 4.2.5 on 2023-10-04 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0008_othertext_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='othertext',
            old_name='likes',
            new_name='like',
        ),
    ]
